package com.paritoshpal.restaurantservice.domain.mapper;

import com.paritoshpal.restaurantservice.domain.RestaurantEntity;
import com.paritoshpal.restaurantservice.domain.models.CreateRestaurantRequest;
import com.paritoshpal.restaurantservice.domain.models.RestaurantDetailedResponse;
import com.paritoshpal.restaurantservice.domain.models.RestaurantResponse;
import com.paritoshpal.restaurantservice.domain.models.RestaurantUpdateRequest;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(componentModel = "spring", uses = {MenuMapper.class, RestaurantAddressMapper.class},
nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface RestaurantMapper {


    RestaurantResponse toRestaurantResponse(RestaurantEntity restaurant);

    RestaurantDetailedResponse toRestaurantDetailedResponse(RestaurantEntity restaurant);


    @Mapping(target = "id", ignore = true) // ID is generated by the database
    @Mapping(target = "createdAt", ignore = true) // Handled by @CreationTimestamp
    @Mapping(target = "updatedAt", ignore = true) // Handled by @Update
    @Mapping(target = "menus", ignore = true) // Service layer will handle menu mapping separately
    @Mapping(target = "address", ignore = true) // Service layer will handle address mapping separately
    @Mapping(target = "rating", constant = "0.0") // New restaurants start at 0.0 rating
    RestaurantEntity toRestaurantEntity(CreateRestaurantRequest createRestaurantRequest);


    @Mapping(target = "id", ignore = true)
    @Mapping(target = "email", ignore = true) // Email is not updatable via this request
    @Mapping(target = "ownerId", ignore = true) // Owner cannot be changed via this request
    @Mapping(target = "rating", ignore = true) // Rating is updated via a separate calculation logic
    @Mapping(target = "menus", ignore = true)
    @Mapping(target = "address", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateRestaurantFromRequest(RestaurantUpdateRequest request, @MappingTarget RestaurantEntity restaurantEntity);
}
